### ISSUE TITLE
dbdsn examples

### ISSUE THREAD

**Issue by llevi** [rkojedzinszky/postfix-ratelimiter#1]
Example for the "dbdsn" syntax is missing.
I don't know how to connect to postgesql database.

**Comment by rkojedzinszky** [comment]
A postgres example is shown [here](https://github.com/rkojedzinszky/postfix-ratelimiter#dynamic-rateburst). Howewer, that connects to localhost (only). The same paragraph contains links to external resources where the full syntax can be found.
